# Chapter One

No one was suggesting that the dead were still alive, or that the dead—by virtue of their having once been alive—did not vanish and cease to exercise an influence over the world; or that the dead’s having lived somehow exempted them from a tax status that was in the strictest sense exclusive. No one was suggesting that it was not one of the axioms of history that, in order to have died, one must have first been alive for a time; and yet this “having been alive for a time” did not confer upon the dead the properties that are, quite demonstrably, within the purview of those who were still living (and who, by that property, had not yet been annihilated)—the shifting of eyebrows, for instance, or the moving of one’s limbs without the aid of an accomplice, or the holding forth amicably on topics of interest to agreeable gentlemen everywhere, or …active measures in the memories and pre-cognitive spaces of an all-too-impressionable public life, and so forth. No, it was absurd to call “dead” that which continued to color the thinking and pronouncements of agreeable gentlemen everywhere. Even supposing the names of the dead were allowed, by some accident of bookkeeping, to persist beyond the death of their referents, merely by their having persisted on certain municipal tax rolls, for instance, this did not imply that the referent persisted, or that any connection between referent and name persisted, by which means the living could “remember” the annihilated soul, invoke their memory at political meetings, and such. For it was plain to see that No, these were apes and imposters of the dead, still subject to annihilation, with names that could be written down and compiled into lists.
But Chichikov knew that the dead could not be killed again. You could not exhume the dead and induce a second death upon their already dead cadavers.
and that, by that byzantine logic, the dead had  had not never existed at any point in time
He knew, on the one hand, that the dead, merely by their being dead, did not vanish altogether.  The dead left a mark—the little divot of air marking their having once been alive—and that this was very different from people who didn’t exist.

 [seed form of this byzantine logic: art. 128 vs. US Institute for Peace , which emerges from the depths of the novel’s subconscious much later on.]
Now the coals
Now the coals had died down, and the pipe smoke rose and took unknown shapes in the darkness above their heads. For a long time now, the mantlepiece clock above the fireplace had been lost in the upturned shadow of the mantle, and Manilov could not tell the hour.  Even so, it had been possible to keep a time of sorts by marking its passage in terms of silent intervals between agreeable commentaries and clever turns of phrase. These silences had gradually dilated,    Manilov made as though to speak and mark the end of another measure of silence, but instead descended into a fit of coughing. Only the dancing pools of shadow were visible on his guest’s face, and not his guest’s face. The eyes of the two gentlemen deepened into little pools of shadow that flickered and steadied by turns, like murder weapons resting at the bottom of remote forest ponds; and Manilov pinched his lapels between thumb and forefinger in a fresh affectation at speech, instead descended into a fit of coughing. Each successive utterance was a mannerly shell of, and difficult to tell apart from, the utterance that preceded it, but had no connection to the previous commentaries, nor to anything else in the world, as regards logic and meaning.
Manilov was able to mark the evening’s passage by the intervals of silence punctuated by amicable utterances.  The successive utterance had little connection to the previous as regards meaning.
Now the coals had died down, and the eyes of the two gentlemen deepened into little pools of shadow that flickered and steadied, like murder weapons resting at the bottom of remote forest ponds; and Manilov pinched his lapels between thumb and forefinger in a fresh affectation at speech, instead descended into a fit of coughing.  For a long time the clock above the fireplace had been lost in the upturned shadow of the mantelpiece, and it had not been possible to tell the hour.  Manilov had maintained a subconscious tally of the evening’s passage in terms of silent intervals between agreeable commentaries and clever turns of phrase.  These silences had gradually dilated,    Manilov made as though to speak and mark the end of another measure of silence, but instead   but was immediately checked by the disturbing sensation of not knowing how long the most recent silence had lasted, not knowing the hour, no longer being able to judge with any certainty for how long he had been staring absently into the consummate darkness.  And instead of the words he had formed his mouth to utter, he choked on a bit of his saliva and descended into a fit of coughing, whence he nearly did not extract himself.  Only the dancing pools of shadow were visible on his guest’s face, and not his guest’s face.

Collected his hands into a little cairn shape atop his knees.
