# Chapter 2

<!-- WE RECOGNIZE on the earth the rolling contours of country fields, the windscorched green and brown tufts of wheat and heather, and their borders of still denser copse, born more of the idea of property than of the earth itself.  Between the masses of landed property run the thin cataracts of road owned by the municipal state, and carved across the particular fields are the foot- and cart-worn paths of the serfs.  At the highest points of the land are perched the manors and mansions of the aristocracy.  Besides these positive aspects, there are, here and there, the numerous absences and silences of little note (in no particular order): no birds singing, no leaves on the trees, no scenes of animals, no centers of social commotion, no souls. -->
<!-- Chichikov pressed is face against the window of the light spring britzka. No souls? Where were the little, smashed roofs of the peasantry? The estates were clear! And yet, who had made those furrows in that field? Who had gathered the hay into the barn over there? This was the distinguishing mark of Rus, setting it apart from other nations. In Rus they had achieved what the Englishman could only dream of: a yeomanry that existed and didn’t exist…. Just out of view, just out of the corner of your eye, in the places where one could not look, were the correct symbolic domain architecture, and also from time to time the things which are not, in the end, actually there.   -->
<!-- Above, clouds pass by in phased banks of disarray—the scattered ranks of some vanquished army—and are the only suggestion to the eyes that time has not stopped [connects with: “but it was easier to stop time”]. Behind this, the pale tablet of sky forced itself onto the literary space in an unending, unwanted tryst, punishing those who gaze up at it with a splitting pain in the forehead. Maybe just one patch of blue sky behind the right shoulder of Christ Pantocrator who offers an enigmatic greeting from the cathedral zenith, framed by spiraling babies and saints, raising his right hand in enigmatic mudra with his fingers. “Is He  flipping us off?” marvels the passing traveler. But no, Christ is not flipping us off.  The aural space, meanwhile, is occupied almost exclusively by the staccato gusts and blusters of the wind which all year does not cease accosting the face of land and people, and even seems to aspire to the totality of silence itself. And in those instances when the wind stops, one is overwhelmed by the silence which is even harder to hear; and to which one cannot close one’s ears. -->
<!-- These were some of the general elements describing, in broad strokes, the ambient sphere of rising action. -->

Now the mansion appeared atop a knob in the distance, like a fly which suddenly alights atop a pile of shit, and the proprietor of the estate, I believe I already mentioned his name—a certain Monsieur H—k, whom Chichikov had met at the recent governor’s soirée—issued from the door in his pajamas to greet our hero, his pate bared and his carrick thrown devil-may-care over his frock and jacket—clearly, he was impatient to understand something.  He approached Chichikov, who had himself scarcely stepped off of his sideboards, at an urgent pace, but held up at three meters or so, and did not extend his hand in greeting.
“Oh, have you forgotten something?” he asked.
“But I have just gotten here!” replied Chichikov.
“Just gotten where?”
“Here!  Where else?”
“But...”
And the two men let a silence pass between them, each one scouring the other’s countenance for the secret meaning that was at play.  At last, M. H—k broke into laughter.
“Ha!  Such a joker you are, Monsieur Chichikov, dear me!  You really know how to hang noodles from our ears.  And with that revizor face of yours, who would ever know!  Ha ha!”
But Chichikov was not laughing.  “But I’m serious,” he assured him, “I just arrived at your estate now.”
“Ha ha!  Ha!  Ha!  Yes indeed!  I know you’ve just arrived, indeed!  Ha!”
“No but, I’m terribly sorry dear host, it’s not a joke.  You see.  I tell you in all earnestness, with all the sincerity of my being, I have just arrived at your estate.”
“Just arrived?  But…then…are you sure?”
“I’m terribly sorry, but yes sir.”
“But, well then, I suppose it’s possible.”
“I should say so…”
“But, well, then please excuse me.  How embarrassing, if I had known, I would have dressed.  It’s just, the resemblance is striking.  Yes, well, please come in.  And what is your name, good sir?”
“I am Pavel Ivanovich Chichikov.”
	At this the host lay himself gently on the ground and clutched his stomach tightly, kicking at the small stones and rubble of his driveway.  “Haaaa ha!  Haaaaaaaaa ha!  Yes, it was you all along!  Ha!  Ha!  Ho!  Yes, oh dear, I was not wrong!  Ho ho!”
	“But, forgive me, dear Monsieur, I haven’t the faintest clue about what you are implying.”
	“Not the faintest clue!  Haaaaa!—”
	“Please, Monsieur—”
	“Ha ha ha ha!  Ha!”
	“An odd fellow,” Chichikov murmured to himself, and turned to take his departure.  But just as he mounted his britzka, the laughter all at once ceased, and he heard H—k raising himself from the ground; and indeed, turning around again, he saw his host upright, staring quite seriously at the road below.
	“But that is your britzka there,” he pointed, “driving along the road to N.”
	Chichikov looked and saw that it was true.  A light spring britzka, which was not at all unlike his own—indeed, which was exactly like his own, and no different—plied its way down the road to N.
“You see,” said the host, “I thought you were him there, come back for something you’d forgotten.  But now I see that he is quite clearly on his way into town, and has not returned…I mean to say, clearly it is evident now that you are not him, there in that britzka, but an altogether different Pavel Ivanovich Chichikov, here.  Though you are identical in every respect, though you have the same name, the same britzka, the same physiognomy, all this must be pure coincidence…”
“I’m sorry!” declaimed Chichikov indignantly, and took one step backward toward his britzka, then another, quickly, as if the sudden masque of identity was simply too much and he must flee immediately.  But he vacillated, and when the decisive moment had passed he said again, “I’m sorry,” but in a tone resigned to his presence at M. Sobakevich’s estate, “I am not that man.  If his name is also Chichikov, so be it; I am innocent of it.  I have no associations whatsoever with him, whatever the outward parity…”
Monsieur H—k looked up through the little storm of data into Chichikov’s eyes, which surged presently with a tender suffering.  And with these words, our hero closed the remaining three meters and took H—k’s elbow in hand; and H—k offered no resistance, and was led up the front steps and through the door of his mansion.
The chestnut mare named Assessor, meanwhile—who remained harnessed to the britzka all this time—held them in her gaze for the whole time it took them to ascend the steps and enter the house—and then shook her head and let out a snort, as animals do when they have witnessed strange scenes.
<!-- Target Class: Hard ICBM Launch Silos and Primary Bomber Bases -->
<!-- Aleysk (SS-18) ICBM Field: 26 SS-18 MOD3 (Satan); 52.28 N Lat. x 82.45 E Long.; Target Hardness- 7000 psi; Background Radiation- Normal -->
<!-- Derazhnya (SS-19) ICBM Field: 20 SS-19 MOD3 (Stiletto); 52.28 N Lat. x 82.45 E Long.; Target Hardness- 7000 psi; Background Radiation- Normal -->
<!-- Dombarovsky (SS-18) ICBM Field: 175 SS-18 MOD4 (Satan); 50.46 N Lat. x 59.32 E Long.; Target Hardness- 7000 psi; Background Radiation- Normal -->
<!-- Imeni Gastello (SS-18) ICBM Field: 18 SS-18 MOD4 (Satan); 51.90 N Lat. x 66.21 E Long.; Target Hardness- 7000 psi; Background Radiation- Normal -->
<!-- Tartu AFB: 15 TU-95 Bear G Aircraft; 58.23 N Lat. x 26.43 E Long.; Target Hardness- 40 psi; Background Radiation- Normal -->
<!-- Engels AFB: 20 TU-95 Bear G Aircraft; 51.29 N Lat. x 46.12 E Long.; Target Hardness- 40 psi; Background Radiation- Normal -->
<!-- Mys Shmidta AFB: 10 TU-26 Backfire Aircraft; 68.53 N Lat. x 179.25 E Long.; Target -->
<!-- Hardness- 40 psi; Background Radiation- Normal -->
Upon entering the house, Chichikov noticed nothing out of the ordinary by provincial standards.  The entry hall, vestibule and parlor were mostly empty and vacant, although bearing the clear scars of numerous attempts to fill it with life of some sort: a wall covered with portraits and scenes of all sizes which were completely covered over with soot, and which bore various inscriptions at their bases, such as “Zukhov” or “Conference at the Crossing”—but what the conference was all about remained a mystery; everything had to be guessed from a pair of hound legs sticking out at the bottom left corner.  Or, alternately, in the frame next to the “Crossing” stood a greaved pair of slim human legs, beneath which was inscribed in flourishing script something like: “Alexander the Great.”  A number of chairs and tea tables grazed about the center of the carpet, meanwhile, and had even worn through the floral pattern in some places, leaving behind threadbare patches through which the wood floor could be glimpsed.

but I cannot grasp…excuse me…I, of course, could not have received such a brilliant education as is perceivable in your every movement; I have no lofty art of expression...Here it may be…in this explanation just expressed by you…something else is concealed…It may be that you were pleased to express it thus for the beauty of the style?”  “No,” said Chichikov, “I mean the matter just as I stated it—that is, those souls which have died, but who would, nonetheless, be counted on the census as living.”  At all of this M. H—k remained silent for several moments, and brought his hand to his chin, where there was a little beard.  “And for what reasons do you need this, Chichikov?”  “You ask, for what reasons?  These are the reasons:


<!-- [falls out of house:] -->
<!-- 	But before Chichikov could proceed, he noticed, presently, that he had fallen out of the house. “Blast!”“But…wha—!  It seems that I have fallen out of M. H—k’s house!  Pah! Well, nothing for it: I must once again enter the house!”  And he set out forthright to accomplish his task; but just then a breeze whispered through a tall walnut tree that stood over the corner of the house, and the walnut tree, which though he did not realize or accept it was the projected logic and inevitable course of his neurasthenia, sent down several volleys of spiny walnuts which barred his path, and he was forced to detain his steps.  But the depth of what was hidden beneath all this masque was as though unfathomable, and our hero’s stubbornness was as though inexhaustible; like those who, after the Revolution, seemed so intent on smashing themselves to pieces against the new reality.   He bunched up the collar of his cranberry colored, swallowtail jacket over his head for protection and continued forward, thrusting out his hand in desperate reconnaissance.  But just then the breeze lifted in intensity, and walnuts came blizzarding down upon his position, preventing him from advancing further.  “Blast!” he cursed.  And he peaked out from beneath his dinner jacket to see where he was, but in the same instant a walnut pelted him square in the forehead.  “Ah!” he cried, retreating still further into his dinner jacket.  Now he heard a soft crunching sound from underfoot, and emerging from his dinner jacket he espied that he had entered a small deciduous grove.  “Blast!” he cursed.  He knelt down in the frosty detritus and opened his attaché case, pulling forth a plume and inkwell, and a ledger with the word “Discrepancies” written across the cover, and setting these implements across a tree stump, he turned the ledger to a blank page and began to make an entry. -->

Now the mansion appeared atop a hill in the distance, like a fly which suddenly alights atop a heap of shit, and the crooked lanes and gardens where Manilov kept his souls began to emerge into view.  For reasons not yet revealed to the reader, Chichikov leaned forward on the seat of his light spring britzka and began counting their broken roofs; but his calculations were immediately interrupted by yet another feature of the passing landscape—this time a hillock atop which a small group of hounds had congregated and was baying into the sunlight.
	“Fools!” exclaimed Chichikov, shaking his fist at the innocent animals.
	After this, there was another bend and dip in the drive, and another small forest with ducks.  One last section of towering black copse tapered off to a thin jetty of trees, and then the britzka turned up the last stretch of hillside to the front steps of the mansion, where the proprietor—whose name I have already had occasion to mention,
