# Chapter Three

ALL AROUND lay a sea of golden gray, which even crested and broke against the little berm of road which the light spring britzka traversed.  At the top of a knoll in the distance, a hound turned placidly about a spot on the ground and lay down.  Behind that, a solitary house rose up into view with bean rows planted in its front yard.  Then, further on, there were some goats being driven over the crest of a hill, with little twitching ears and noses.  Then there were some small houses which emerged from behind the forest and came gradually into view.  Indeed, the little houses themselves resembled a small herd of goats which had just been driven over the hillside and then frozen there by the spell of some Greek god, with little beetling ears and noses that resembled windows and stovepipes.  A settlement of houses came up on the right, presently, with one of the barn doors opened onto a threshing floor, where a pair of women were busy with the harvested sheaves.  Chichikov glimpsed their rosy arms flashing in the low auburn light before they snapped out of view.  Then: In front of one of the houses a mother reached down and scooped up a small child into her arms, heaving her up into the air.  Even at this distance the black hair of the two figures stood out from the black doorway that framed their sudden apparition.  But already the whole scene began to wink at Chichikov through the tall golden-grey grass as his britzka descended into another vale, and was gone.
You looked and looked again.  But what was it?  What was this strange sort of something-or-other that was there.  We listen in for the answer, but no answer comes forth.  “Well I,” pipes up someone sitting on the parlor sofa, but then immediately remembers they are drunk and falls silent.  But such was Rus!  A laugh and a glimmer in the eyes—and like a racing troika it is gone!  One looks again, but there is nothing.  Only laughter and swirling snow give any evidence that there had been something there—whatever it was—and then the laughter and swirling snow also dissolve and vanish into nothingness.


[corporal:]

Chichikov drew to the side of the road and descended the light spring britzka; and drew himself up at the edge of the roadside.  He peered into the field; but it was almost—there was something there—he looked again a second and third time: the fields were there.  And there were some trees.  Further on, some goats could be discerned.  Chichikov gazed and gazed into the field, with a certain air that was at once deft, staid, and agreeable; there was a certain flare of the nostrils—but just what the devil was it?  Some remark was called for, some clarification, but no such remark was forthcoming.  Behind him a sudden gust of wind lodged in the high boughs and made a howling, clattering ruckus, and Chichikov turned around to watch the little leaves that still clung to their branches.  He looked up into the last autumnal leaves: they were just little brown and gray leaves, fluttering in the breeze.  He trained his gaze on the little diamond-shaped frames of their intersecting vines and branches, which criss-crossed and intersected to form rotund little diamond frames of sky and leaf, and saw: more intersecting vines and branches, which enclosed further diamonds of sky.  He peered into the little diamond shaped frames of vines and branches.  It was all nameless, of course, made-up nonsense, frozen, dead.  And yet it was all there; and there was no other way to put it than the way it was.  Chichikov staggered backward and vomited briefly in the grass.
After this, the light spring britzka drew up to the steps of the mansion

The two gentlemen swept off across the grass pitch, then, staggering down the little rut of heath, their little hairs swept up and battered about like little sails on the quay, making it difficult for them to keep their footing.  Distant mooing and clatterings of mule hooves reached their ears from two or three directions at once, divided and reconstituted by the wind.  Further on, beyond unwanted outbreaks of copse and forest growth, the cultivated shards swept together into a vast brown sea extending onward through one province after another until—but just until what was not known—following the downward slope of the flowing sheaves of grain where they ran against a broken down fence, and beyond that Chichikov saw a subsequent field extending almost to the horizon where a distant herd of black goats peeked bashfully over the—or no, now he saw correctly, those were the little houses of the serfs’ village.
“Here are my ducks,” said M. H—k somewhat diffidently, as though not quite sure where to begin.
A turkey, meanwhile, who was among the fowl, began bobbing his head up and down meaningly, and slowly accosted our hero.  Chichikov feigned indifference—as when one has been recognized at a crowded gathering by someone one doesn’t wish to talk to.  But then his hand was forced by a sneeze, and the turkey exclaimed something which sounded very much like “God bless you!”—to which Chichikov responded, “Fool!”
“That fence down there,” said Chichikov, pointing; and they staggered down the heath rut toward the low row of stones.
When they reached the little pile of stones, Chichikov pursed his lips and laid his hand on one of the stones with such forthrightness that Monsieur H—k was deeply impressed; he forgot his concern, and also stepped forward, and took a stone in hand, his eyes glazed over with deference.
“This fence needs mending in several places,” he said, “I shall rebuild those storage sheds over there.  And I shall rehabilitate those fields lying fallow over there.  And that area will be cleared for pasture land…”
They stood at an excellent vantage over the land now.  Chichikov saw the trees swell abruptly into the foreground and then recede behind the crest of land behind them, watching them closely.  He saw the trees accreting and gathering into the foreground, and then decrescendoing and vanishing beneath the rising horizon line of wheat sheaves to his right and a little behind him.  There were the intermittent groupings of two or three or, for example, five trees, intermittent at first—indeed the whole of the serfs’ village was enclosed in one such arboreal caesura—and then less intermittent so that it was a forest.  Chichikov threw a furtive glance back at the forest which he had scrutinized before.  Still everything was in place, and he returned his gaze forward.  He swung his head backward again, as if to catch the existence of the forest off guard.  But again he was rebutted by the actual presence of trees and field; and a jackdaw which sat overhead on one of the branches even cawed down mockingly at his vain efforts.  Yes, thought Chichikov as he surveyed the landscape one more time, there was nothing that was not there, that was not somehow present—nothing that would reveal some secret, some special character, that was different from immediate appearances, that had been hidden at first.  No, there was nothing that was not qualitative, that was not, somehow—it all stubbornly refused to be something else besides what it was, no matter how resolutely and meaningly one gazed into the obtained field.  Our hero staggered backwards and paled, and vomited into the tall grasses.
 “And the new chapel will be built on that hillock, over there…” continued M. H—k, meanwhile, oblivious, “…and I shall construct a hanging gardens there on that knoll—”
“Whether you do these things or not is fine by me,” said Chichikov, “but you must always guard against both doing them and not doing them.  That goat, for example, over there, or that grove of trees down there, must not be allowed to be two goats, or two groves of trees.  You can get another goat or plant another grove alongside that one, but just so long as it is a different grove, and not the same as the one that is already there.  If you do get more goats, fine, but you must ensure that they are new and different from the goat you already have.  You must never allow yourself, Monsieur H—k, to come into possession of a goat which is the same as that goat down there.”


The ghosts of the past were harmless digressions; and since the past in which they took place no longer existed, they themselves can no longer be said to have taken place.  Chichikov knew for example that the dead could not suddenly burst out of the earth and come get you, and drag your soul down to hell.  They were not there waiting to reach out their flayed arms and pull up your soul like a little turnip.  Like this, Chichikov’s thoughts went out and peopled the confines of his gaze.  Objects, too, seemed to mingle.  The only problem was whether you were really yourself, or whether you had become the ghost of yourself and were one of the ones who deserved to be dragged down to hell.
After this, the mansion appeared atop a knob in the distance, and gradually came into view.  Three English gardens were planted on the slope, beside which sat a squat gazebo of some brownish color, enclosed, in its turn, within a pentagonal arrangement of lattice gates—a structure, perhaps, with pretensions to being an arboretum of some sort, over which was hung a wooden sign that read: “The Pentagon of Solitary Contemplation.”


Chichikov gave a little laugh and continued striding down the turbulent grain heath, knowing too well the pageantry of meaning and agreeable gentlemen.  Still, it was just the sort of remark that he found paltry, facile—unworthy, at any rate, of the repertoire of agreeable gentlemen.  He could not help that his bile was turned, and he turned and spat briefly, sideways into the wind; and some of the frown that was in his heart found its way up into the corners of his lips, which began twitching sporadically, with the result that there once again appeared on our hero’s face a look of spectacular meaningness, such as can only be seen at Petersburg dinner parties—it appears to be some sort of roguish bemusement at first, but in the next moment God alone can say: it’s not neurasthenia; it’s not epilepsy, nor even some demonstration of magnetic properties—devil knows what it is!  He turned aside and vomited briefly into the heath.


Chichikov selected the chair with the most upholstery, behind which a little fire scowled and crackled from the hearthplace, and sat down—immediately he shifted so that he was sitting not in the center of his seat but to one side, with his legs cast out in front of him obliquely; and his hands and kneecaps folded on top of each other so that they formed a delicate cairn shape at their pinnacle, which was very striking to the eye.
But Chichikov’s concentration was boken, presently, by a gentle hissing noise which filled the room, and he looked about himself for several moments afraid that snakes might invade the room.  But then he realized that the hissing noise was coming from exactly the center of his host’s eyebrows, which were shifting slightly to and fro.  Indeed, M. H—k had even transfixed our hero rather sternly in his gaze, and Chichikov began to worry that the light and agreeable mood between them had been soured somehow.  He settled back and cast his gaze about the room to try to restore something of the meaning and congenial atmosphere that had flourished just moments before; he drew in his legs and cast them out again several times, until only the hindmost portion of his posterior remained in contact with the chair.  But in the same instant, M. H—k, too, collected himself unto some inner, private principle; and sensing something of our hero’s inner vacillation, he anticipated him:

At last Monsieur Manilov descended into a fit of laughter that was at once, somehow, glib and earnest; and Chichikov joined in with a light chuckle of his own, and the two laughters crescendoed and grew together; while at the same time casting sidelong glances in each other’s direction and raising their glasses into the air. Then the chuckling tapered off and they were once again engulfed in the nothingness whence they had set out. M. Manilov struck a wistful gaze upon his fields, which were visible through the window beneath a light mist.  “And so then, if there are no obstacles, we might proceed then…with the purchase?”  “Purchase?”  “The dead souls, that is…”  “Ah!  But…”  And here Manilov gazed meaningly into Chichikov’s face to catch the ironic intent that was at play.  There was as a matter of fact no such ironic intent, but Manilov ignored this detail…Chichikov swooned and gave such a violent twitch in his seat that he nearly burst the fabric of the cushion beneath him.  Finally, he even gave a little leap after the manner of the goat, who are known to perform such leaps only under the strongest impulses of joy.


The two gentlemen rose and ascended the staircase to the study on the second floor, then, and took their seats at the little green table, where the game of whist was set out.
“How long ago were you so good as to file your census report?”
“For what reasons do you need this, Chichikov?”
Chichikov sat not in the center of his chair, but slightly to one side, with his legs cast out obliquely, at an angle.
“For what reasons do you need this, Chichikov?”
“You ask for what reasons?” picked up Chichikov, but hesitated immediately.  There even appeared on his face a strained expression—the strain of expressing something that is not quite amenable to words—which even made him blush.  And the longer he hesitated, the stronger became the raspy whisper which was emanating from Monsieur H—k’s eyebrows.  The noise, indeed, was on the point of driving our hero out of his mind, when all at once he drew himself up and said:
“These are the reasons: to have in hand the list—the census—of those who were erroneously registered as …to know, that is, which of us are still real, even though we think we do not exist.”
At these words, M. H—k shifted his eyebrows with such fury that they emitted a noise such as is only heard at green tables when a deck of cards is being shuffled; and our hero looked at the cards in his hand to see if someone hadn’t indeed, by some furtive and stealthy gesture, entered the room and shuffled them.  But no, no one had done so, and he smiled amicably.
 “But Chichikov,” cried M. H—k meanwhile, who had stood up from the green table and turned to face the portraits of Nicholas, Zukhov, and Bagration that were on his wall, “that is illegal!”
“Illegal?  But—”
“Mortgaging dead souls to the bank as though they were living—Pah!”
 “Well, as you’ve been so forthcoming, I’ll let you in on a little secret of my own, hm’mmm, a little confession of my own just maybe hmm’mm, indeed!  Oh yes yes, these epaulettes you see here on my shoulders, hmmm, and this Cap’n Crunch hat you see on my head, these are not just leftovers from the campaign of ’12, no no!  And just, h’mm, for your general information, hmm hm’mm, I should like you to know that if this person to whom you are talking, who is standing in my shoes, if he happened to be, it turned out, by the remotest chance an authentic police left-tenant…well, then I can assure you, so that you might not be disuaded from knowing, on that very unlikely occasion, that that putative corporal who we must admit, for all intents and purposes almost certainly does not exist, would in those remotest of circumstances…hmm…”
But H—k presently became so lost in his ironic use of the third conditional that he was unable to distinguish between himself and his ironic portrayal of himself as not himself, and he convulsed briefly in a decrescendo of slathers and murmurs, and fell back into his chair, inviting Chichikov to a game of whist upstairs.
“But my dear host!” exclaimed Chichikov, “we are already playing whist upstairs right now!”


[…Why, just then a literary hack sitting in a coveted departmental chair in some European captial was musing:] But the novel, somehow, is always something else from itself, leaving behind, like footsteps, a trail of dreamy semblances which do not measure up to the whole.  Some will say, surely, that something must be happening in this world, which is only what it is—some sort of loamy development and budding lyrical foment—but it is not even so much loamy development, but rather some sort of primary main thing, some main sort of primary happening thing, which is what it is.  Indeed a novel, and the same is said to be true in painting and sculpture, must be only its authentic self, and not different things that are not the same as what it is.  And something is happening, surely, we must confess: the wind howls and the pine trees give a shudder, the fields of grain crest and surge like an ocean—But everything that is not what the main sort of primary thing is, sweeps to the fore unwanted.  Something, indeed: everyone and everything carries on, but beneath the surface no one can remember what it was.  The primary sort of main thing is gone, suddenly—it was never there—and all of the things that were not the main thing sweep to the fore; the unwanted tide of everything that was absent until then and that did not exist, sweeps to the fore.  It is only natural, then, that the novel, as a form, appears at so many points not to be what it is.  One will say, naturally, but if it is not a novel, then what is it?  If this is not the loamy foment and the majestic lyrical flow, then what is it?  We listen in for the answer, but no answer comes forth.  “Well I,” pipes up someone sitting on the sofa of the parlor, and immediately remembers they are drunk and falls silent.  But such was Rus!  A laugh and a glimmer in the eyes—and like a racing sled it is gone!  One looks again, but there is nothing.  Only laughter and swirling snow give any evidence that there had been something there—whatever it was—and then the laughter and swirling snow also dissolve and vanish into nothingness.

