# Chapter 4

Chichikov knew that there was the one...

Chichikov knew that …aple, oak, and birch leaves fell uniformly to a crimson and golden carpet that covered the forest floor; and Chichikov beheld the swirling lattices of crisscrossing trajectories of autumn leaves with flat affect. The room that enclosed him was featureless and remained unfamiliar to him, but threatened to become familiar each time he allowed his gaze to rest in any single place for more than a few seconds. This was the solace he found in the staid business of falling autumn leaves crisscrossing at scalene angles, ordered but unrepeating, an argument against (re-)collections of components equipped with properties of coherence and consecutiveness, and hence against remembrance, which he knew was a subset of these, by which the passage of time itself was disabled, and with it the forces of remembrance disarmed. The point of his every gesture, physical or mental, was to resist the tide of cognition welling up within—the recognition of suppressed contents, the connecting of dots, the identification of patterns, correlations, textures, tessellations, the gathering of random shards of quicksilver into coherent mirrors—in a phrase: the firing of neurons. His error all along had been of finding a way to disable the decipher-drive of consciousness, when all that was needed was to disable time.  He had found this window, at least, of falling leaves, by which he could turn off time for himself.  But he knew the tide of cognition arose from without too. Somebody would call at the door, usher him to his appointments and evaluations with Dr. Hank. He allowed himself to fantasize that he would just invite whoever came for him to look out the window, and watch their intentions and any recollection of who they were and what they had been sent to accomplish come unframed, just as his own notions of himself and of “what happened” had come unframed, and then wait for the next person to come for the one who had been sent and entrance them too, and so on with the next one and the next, until time had stopped for the entire world. By modern standards, this was not in fact an outrageous idea, and may have worked had it not been for his own diffidence in the plan.
	Chichikov knew that there was a difference between depictions of things and the things themselves that were depicted. He knew that no matter the intensity with which one gazed at the page of text describing some real or imagined occurrence, the assembly of ink symbols and intervening blank paper fibers on the page would never be the same as the meaning that the ink symbols and intervening blank paper fibers had been arranged to convey. You could watch a leaf fall to the ground, for example, and then draw a picture of your recollection of the event, but you could not then watch the drawn leaf fall to the ground, no matter how intently you gazed at it. Skillful artists could convey the sense of abstract or immaterial natural phenomena, such as an autumn breeze, that then invoked in the subconsciousness of the viewer a sense of before and after, and thus a dynamic illusion of one moment following consecutively after another, even when it was plain to see that all there was was ink and paper. One allowed oneself to be drawn in and immersed in the illusion Skillful observers of skillful artwork should then have no trouble, reasoned Chichikov, reverse engineering the process, by which the skillfully conveyed but false impression of movement and time passing could be neutralized, revealing the true nature of ink and paper beneath the scene. Chichikov knew that “skillful artwork” was, in the limit, Creation itself; and that it must follow that the “skillful artist”, in the limit, was the Creator, Christ Pantocrator, seated at the top of the sky, or rather at the top of the skies so skillfully depicted at the tops of Byzantine cathedral domes. It only remained, then, to take the limit of the “skillful observer of skillful artwork”, and one would arrive at the observer capable of recognizing the unmoving, timeless medium beneath the Illusion of Artful Movement…the poignant
Say you were standing before a painting of some autumn scene in some illustrious museum where such works are kept, for example, thought Chichikov, going over in his mind how he would convince whoever came for him to look out his window and understand that the autumn leaves were not in fact falling from their branches, that, in fact, nothing at all was happening; that is to say, that time had stopped. The abstract feeling of an autumn breeze is skillfully conveyed in this painting you are hypothetically looking at in the museum, he went on to himself, by which you get a sense of autumn leaves shaking loose from their boughs and sailing to the ground. And yet nowhere you looked, in any direction, are there in fact any real leaves falling to the ground. You feel no breeze, hear no rustling of leaves. In fact, it is plainly evident that there is is paint and the canvas on which the scene is painted. But you have a good look, and are drawn in by the mimesis. Who is to say you yourself are not some concoction of fabrics and pigments? You looked up again at the leaves fluttering on their branches, and struggled to see one come loose and sail to the ground on the light autumn breeze, but again and again they just remained there, fluttering on their branches; and then when he looked and saw that a leaf had come loose and was sailing to the ground, it had already come loose from its branch before his gaze alighted upon it. You could tell by the way that the branches were that a tree was present.  You could tell by the way the leaves curled over on themselves that a breeze was present; and yet none of the leaves finished sailing to the ground. Was it that none of it at all was there?  If you could just remain unaware of what it all was, then things continued on normally, but as soon as you tried to know what it was, and to see the leaf, the leaves froze where they were, and did not finish their descent; and the mist further on, and the layers of magenta light weighed on the landscape like heavy sacks.  The world became dead, hard, difficult to figure out. The moment froze and did not carry on to the next moment. But you are philosophically inclined, you know what terms like “prima facie” mean and “want to get at the essence” of everything. You reach out to touch the breeze, setting off alarms in the museum. You feel that it is dry and brittle and threatens to come apart in your hands, because it is, in fact, the mere fabric on which the scene was painted. And, in that last moment before being apprehended by museum gendarmes, you might even hear something that sounds like the whisper of breeze through autumn boughs, but it is only the whisper of old canvas between your fingertips. And yet when you had a good look, you could not deny the landscapes of copse and mansions on hills in the distance, with some goats further on, randomly congregated groups of hounds sitting in the rain, baying their little hearts out for no discernible reason. Or rather, what you could not deny was your appetite to see and be deceived into seeing these things.
[Like this, Chichikov went over what he would say to whoever came for him.] Again and again, we allowed ourselves to fall for reality’s artful depictions, and the brittle parchment of space and time disintegrated between our fingertips. Again and again, reality failed to be real. A little further on there was another valley hidden beneath a thick mist.  Like this you inferred the presence; there was no way of telling it was there, but it was because of this that you could infer its presence.  It was completely evident that what you had were maple trees, gingko trees, plum trees, and willow trees.  If you just had a look and saw the old crooked branches, and the knotted shales of bark, you knew immediately without a doubt what it was, and you could go back to it again and again and know the reality.  But here was the problem; as soon as you went back and knew what the reality was, the leaves froze where they were and did not sail the rest of the way to the ground.  The trees were still.  There was no whisper through any of the branches of any breeze.  The vermillion layers in the distance staled and weighed on the horizon. You could infer, derive, deduce, draw conclusions about the reality of what was taking place before your eyes, in the same way that you inferred the presence of the breeze, coming closer and closer to the conclusion that none of it was there, that it had never been there.  It was there, certainly, causing you the problem, but it was an absence, a negativity.  Absence, negativity, and emptiness were all there too, Chichikov knew.  Perhaps they were the only things that were truly present.  This was the sort of conclusion your laws and formulations were always headed towards, and then you came up with some new laws to try to avoid that destination.
You could not say, as the museum gendarmes dragged you off, that the leaves had continued to fall to the ground all this time, implying a point in the past, before the leaves had continued, and a point in the future after the point of continuation. You could not say that there was an autumn breeze or that there was a forest outside your window. All there was was parchment, ink, chemical pigments. Likewise, Chichikov knew, you could not say that you were in a museum viewing a painting of an autumn scene or that gendarmes were dragging you off, because these were themselves just words written on a different kind of parchment, no less brittle, emitting a susurrus as the fondling of cognition.. But you had to concentrate hard, for at the same time none of these things were really there. All there was was ink formed into different symbols on paper, ostensibly random, by turns, ostensibly ordered according to hidden, phased lattices of ciphers, by turns, phased arrays of strategic target umbrellas.
